# Generated by Django 3.2.6 on 2021-08-31 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='lang',
            field=models.CharField(default='en', max_length=5, verbose_name='Language'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
    ]
